source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VGCondition_Example', :exclusive => true do
  pod "VGCondition", :path => "../"
end

target 'VGCondition_Tests', :exclusive => true do
  pod "VGCondition", :path => "../"

  
end
